### ISSUE TITLE
Why isn't `channelId` affected by every element of `FixedPart`?

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#124]
https://github.com/statechannels/go-nitro/blob/91fc0e93ad2acd50287bc5a927eb8aa237bb7710/channel/state/state.go#L28-L37

My understanding of `channelId` is that it is meant to protect users from a channel's behaviour changing during its lifecycle. Why can `appDefinition` and `challengeDuration` vary without changing the `channelId`? (If they are truly variable, why aren't they a part of `VariablePart`?)

**Comment by geoknee** [comment]
This is a good question. I considered it before and came to the same conclusion -- the only reason it is still this way was to maintain some backwards compatibility with our existing code (i.e. `nitro-protocol` npm package). Instead of changing it, I put in some comments that make the issue more explicit. 

I suppose changing it might not be too much work... but it would break a lot of tests. It doesn't feel that high priority, to me.

**Comment by andrewgordstewart** [comment]
> I suppose changing it might not be too much work... but it would break a lot of tests. It doesn't feel that high priority, to me.

It seems like a perfect first-issue for a new golang developer. I think I will tackle it!

**Comment by geoknee** [comment]
> ... but it would break a lot of tests

I think I was mistaken to think this. The proposed changes do not affect the channel id (as I had thought).
