### ISSUE TITLE
Closing notification is not fired by "passive" ledger defund participant

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#1317]
> Not a part of this work, but it's a bit confusing that Closing notification is only sent to the participant that initiated the close. Do we know why this is the case?

_Originally posted by @kerzhner in https://github.com/statechannels/go-nitro/pull/1315#discussion_r1207085804_

**Comment by geoknee** [comment]
In my understanding, this is because notifications are sent as the final step when all work triggered by an event has been completed. When the responding participant receives a final state from the initiating participant, it can often be the case that they are ready to countersign and do so immediately. So the notification for "closing" (meaning, there is a final state + signature in my store but not yet a fully supported one) never gets fired. By the time the notification fires, the channel is already "complete".
