### ISSUE TITLE
Why are type aliases used in `types.go`?

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#135]
Reading from https://yourbasic.org/golang/type-alias/, I see 

> Type aliases are not meant for everyday use.

We are using type aliases in `types.go`. Is there a reason for that?

_Originally posted by @andrewgordstewart in https://github.com/statechannels/go-nitro/pull/130#discussion_r781350255_

**Comment by NiloCK** [comment]
Blocking issue seems to be that type definitions `type A B` do not forward methods from `B` onto `A`.

See the following code in the [go playground](https://go.dev/play/p/gaH229UN-0k):

```
package main

import "fmt"

type Foo struct{}

func (f Foo) Greet() {
	fmt.Println("hi")
}

type Bar = Foo

type Baz Foo

func main() {
	foo := Foo{}
	foo.Greet() // works

	bar := Bar{}
	bar.Greet() // works

	// baz := Baz{}
	// baz.Greet() // type Baz has no field or method Bar
}
```

**Comment by geoknee** [comment]
We use type aliases in a few well-chosen spots, so I don't think we are falling foul of the "not for everyday use" advice.

We often want to add "extra sauce" (methods) to another type (which might be imported from another package). This is the case with `types.Destination`, which we have adorned with a `.ToAddress()` method. It's our type, so we can add methods to it.

Other times, the original type is more useful. This is the case with `common.Hash`, which is imported from the `go-ethereum` module and comes with many helpers that we want direct access to. If we defined our own type over it, we would lose access to those helpers as @NiloCK points out. Furthermore, the original type may be the subject of a test during type reflection -- for example, when we use the `go-ethereum` abi encoder, it tests for types from that same imported module. So defining our own type over the imported type would make it incompatible with the abi encoding functions that we want to use. I think all of us have now tried this and been hit with a panic.

So we must use the imported types. But we may like to rename them, since we may prefer to read `Bytes32` to `common.Hash` in our code. That's when we can use an alias, which is literally just a renaming of a type with no other change in behaviour. 

And we may also like to use a type which is defined in a **single place**. The type alias makes this easier -- for example we could re-alias `types.Address` to a different type by making a single line change, rather than doing a find and replace on all (or a large number) of `common.Address` instances.

**Comment by geoknee** [comment]
From a certain point of view, we are using these aliases "every day". But I would question the advice against doing that. If you follow the links in the referenced article above, you get here https://talks.golang.org/2016/refactor.article . Reading that, I feel pretty comfortable using aliases because they anticipate the kind of refactoring that I mentioned above and make it much easier, and this seems to have been the main motivation for introducing them.

**Comment by andrewgordstewart** [comment]
I feel convinced that using type aliases is a good thing here. We can run the decision by Hannah or Perun if you feel any uncertainty.

**Comment by NiloCK** [comment]
I am also comfortable with current usage. One more note for posterity:

![image](https://user-images.githubusercontent.com/10780590/149167950-781f37b7-3694-4e72-8f47-283c4aca49b1.png)

The code-base also uses type aliases when defining the `rawFooType`s used by the abi encode / decode functions. These seem necessary, or at least convenient. Alternatives break at run-time, due to mismatches of types discovered using reflection inside geth's `abi.Unpack()` `abi.Pack()` functions.

As far as I can tell, these functions recreate an unnamed type using reflection, and then insist that it matches the handed-in type, which always fails in the case of a "properly defined" type.

**Comment by geoknee** [comment]
Closing as there seems to be consensus and understanding around this now. We can reopen if necessary.
