### ISSUE TITLE
Optimize chainservice init function

### ISSUE THREAD

**Issue by bitwiseguy** [statechannels/go-nitro#1600]
We should consider updating `lastBlockNumSeen` even when we don't receive adjudicator events in blocks so that our `chainservice` init routine does not have to search all blocks since the last adjudicator event was received.

https://github.com/statechannels/go-nitro/pull/1581#discussion_r1307488870

On the `Calibration` testnet I am running into an issue where this node provider `wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0` can only look back in time ~16 hours. Updating the `lastBlockNumSeen` for each block would allow us to have a downtime of up to 16 hours using that chain url, regardless of when the last NitroAdjudicator event was processed.

**Comment by bitwiseguy** [comment]
Possible solutions:

# Add a `NewBlock` custom event type
We could add this custom event topic:
```go
var newBlockTopic = crypto.Keccak256Hash([]byte("NewBlockMined"))
```
Then could transform a `newBlock` header into our own custom `ethTypes.Log`:
```go
		case newBlock := <-newBlockChan:
			newBlockNum := newBlock.Number.Uint64()
			ecs.logger.Debug("detected new block", "block-num", newBlockNum)
			newBlockEvent := &ethTypes.Log{
				BlockNumber: newBlockNum,
				Topics:      []common.Hash{newBlockTopic},
			}
			ecs.updateEventTracker(errorChan, newBlockEvent)
```
Then within `dispatchChainEvents` we could add this addition `case` statement:
```go
		case newBlockTopic:
			ecs.logger.Debug("Processing New Block event")
			event := NewBlockEvent{commonEvent{blockNum: l.BlockNumber}}
			ecs.out <- event
```
This would utilize the same `ecs.out` chan to communicate with the engine. We would then have to add additional logic to the engine (likely in the `handleChainEvent` function) to process this event type by simply calling `store.SetLastBlockSeen(event.BlockNum)`. The downside to this approach is we have more noise on the `ecs.out` chan. Not sure if that is a huge concern but it does make it more difficult to test because we have to filter through more events to find the ones we want to check.

# Add a `NewBlock` chan
Instead of adding `NewBlock` events to the existing `ecs.out` chan, we could create a new, dedicated `ecs.newBlock` chan for the `chainservice` to communicate with the `engine`. This means we would probably have to add another `case` statement to the `engine.run` loop to handle info passed on that channel:
```go
		case chainEvent := <-e.fromChain:
			res, err = e.handleChainEvent(chainEvent)
		case newBlockEvent := <-e.newBlock:
			res, err = e.handleNewBlockEvent(newBlockEvent)

```

**Comment by bitwiseguy** [comment]
On the `Calibration` testnet I am running into an issue where this node provider `wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0` can only look back in time ~16 hours. Updating the `lastBlockSeen` for each block would at least allow us to have a downtime of up to 16 hours using that chain url

**Comment by lalexgap** [comment]
> On the Calibration testnet I am running into an issue where this node provider wss://wss.calibration.node.glif.io/apigw/lotus/rpc/v0 can only look back in time ~16 hours. Updating the lastBlockNumSeen for each block would allow us to have a downtime of up to 16 hours using that chain url, regardless of when the last NitroAdjudicator event was processed.

It looks like the public lotus node only [support the last 2000 blocks since they use some kind of lightweight snapshot](https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint). That does means if you're nitro-node is down for more than 2000 blocks you're hosed, which is kind of scary. 

>1. Add a NewBlock custom event type

Right now our all our chain service events roughly correspond to on-chain contract events, where the `NewBlock` event would be kind of a special case. The `NewBlock` event would also be handled "specially" by the `engine`. So I think I would lean away from adding a `NewBlock` event to the existing chain events.

>2. Add a NewBlock chan

This seems like a cleaner approach! 

In environments where blocks are mined fast, maybe writing to the store for every block could have a performance impact? That's unlikely to be a realistic scenario though.

>Possible solutions:

Just going to throw in another option to consider. Instead of the `chain service`  alerting the `engine`, the `engine` could request the block number from the `chain service`. Since the `engine` wouldn't know when a new block is created this would mostly likely be done by the `engine` on a timer. The `engine` would also do this when `close` is called.  

 This does means the `lastBlockNumSeen` wouldn't get updated every block, but I think that's ok.  It doesn't matter if the `lastBlockNumSeen` is slightly stale, we just want to prevent it from being waaaaay out of date.

I think the benefit of this approach would be the simplicity. Instead of adding a new chan or event we just need to add a `BlockNum` function to the `chain service`, and call that in the `engine`.   It also means we wouldn't write to the store every block  but every `x` minutes (and when we `close`).

**Comment by bitwiseguy** [comment]
> It looks like the public lotus node only [support the last 2000 blocks since they use some kind of lightweight snapshot](https://lotus.filecoin.io/lotus/developers/glif-nodes/#testnet-endpoint). That does means if you're nitro-node is down for more than 2000 blocks you're hosed, which is kind of scary.

Yea this is definitely something we need to consider. Here are a couple options I can think of:

1. Send a `WARNING` log during the node's initialization if the `lastBlockNumSeen` is greater than 2000 blocks behind the current block. Then we can only scan back 2000 blocks. I don't think the 2000 blocks is consistent across RPC providers though so it will likely be a different limit and I'm not sure how we find the limit programmatically (i.e. I don't think there is any RPC method to discover the limit). Perhaps we do a binary search to find the latest block we can successfully query? If we go this route, would we want to store which block range we were not able to query?

2. Prevent the node from initializing if the query for old logs fails. This would force the user to alter their config file to increase the `chainstartblock` value until it is close enough to the current block num for the query to succeed. This means there could be a gap in blocks queried (similar to [1] above, but this approach would require user recognition/acceptance rather than just a warning log/notification).

3. Force the user to use an RPC provider that allows log queries on any block range (i.e. provides access to archive nodes). Infura is one RPC provider that provides access to archived data.

**Comment by lalexgap** [comment]
> Yea this is definitely something we need to consider. Here are a couple options I can think of:
> 
>     1. Send a `WARNING` log during the node's initialization if the `lastBlockNumSeen` is greater than 2000 blocks behind the current block. Then we can only scan back 2000 blocks. I don't think the 2000 blocks is consistent across RPC providers though so it will likely be a different limit and I'm not sure how we find the limit programmatically (i.e. I don't think there is any RPC method to discover the limit). Perhaps we do a binary search to find the latest block we can successfully query? If we go this route, would we want to store which block range we were not able to query?
> 
>     2. Prevent the node from initializing if the query for old logs fails. This would force the user to alter their config file to increase the `chainstartblock` value until it is close enough to the current block num for the query to succeed. This means there could be a gap in blocks queried (similar to [1] above, but this approach would require user recognition/acceptance rather than just a warning log/notification).
> 
>     3. Force the user to use an RPC provider that allows log queries on any block range (i.e. provides access to archive nodes). Infura is one RPC provider that provides access to archived data.

I think the 2000 block limitation might mostly be a limitation of the glif filecoin nodes and [glif does support requesting your own full node](https://lotus.filecoin.io/lotus/developers/glif-nodes/#fill-in-the-request-form), so I think in most use-cases this hopefully won't be an issue (like you pointed out [Infura provides full history](https://docs.infura.io/networks/ethereum/json-rpc-methods/eth_getlogs#constraints)). So I think a combination of 2/3 would make sense.

I think we want to prevent a node from starting if we know we could be missing event (as specified in 2). Even if this is pretty rare situation, I think we should still protect against it, since missing events could be really bad. Although we probably already kind of handle this; if the query fails the chain-service is going to [panic](https://github.com/statechannels/go-nitro/blob/cfea87e8329362db872500b8513e91254c928c58/node/engine/chainservice/eth_chainservice.go#L192). It might not result in a nice error but it would prevent you running a nitro-node that could be missing events.

**Comment by bitwiseguy** [comment]
@lalexgap I implemented your suggestion to use a timer to trigger updating the blockNum in store in the absence of NitroAdjudicator events that would also trigger that update. Here is the PR for that work: https://github.com/statechannels/go-nitro/pull/1648

**Comment by bitwiseguy** [comment]
I made a request to glif to give us access to a Calibration testnet archive node. Awaiting their response...

**Comment by bitwiseguy** [comment]
This was resolved in https://github.com/statechannels/go-nitro/pull/1648
