### ISSUE TITLE
Make design doc / ADR for restart-capable event tracking

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1604]
> If we already have protection in the Channel class against processing the same event twice

I think we need an ADR for this - a well-thought-through pattern which involves some "contract" between a chain service and the `Channel` class, such that we don't get any bugs around stale or incorrect information.

Example: the `Channel` class promises to have an idempotent function for accepting events from the chain service, and the chain service promises to pass events in order. 

☝️ I'm not 100% sure about this example though. It seems like we might want to avoid (re)playing a `ChallengeRegistered` event if the challenge has long since expired or been cleared. 

Not a blocker for merging this PR, because I think in mose conceivable patterns we will want to store `lastBlockNumberSeen`.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/1581#discussion_r1308449935_

**Comment by bitwiseguy** [comment]
Is there anything that enforces the restriction referenced in this comment that says a `Channel` can only be updated by a `chainEvent` that has a `BlockNum` greater than the block number previously seen? https://github.com/statechannels/go-nitro/blob/main/channel/channel.go#L322

It seems like if we store the `LastUpdatedBlockNum` as a field on the `Channel` struct, then we could add some logic to the `c.UpdateWithChainEvent` method to disallow updates if the provided `event.BlockNum` < `c.LastUpdatedBlockNum`

**Comment by lalexgap** [comment]
>Taking this thought further: do you think we need to consider the case where multiple transactions event emits related to the same channel within the same block?

At least with [`deposit`](https://github.com/statechannels/go-nitro/blob/9888d195fad804e9480dfe3441f8b8df310c95f4/nitro-protocol/contracts/MultiAssetHolder.sol#L37) and the [`Deposited`](https://github.com/statechannels/go-nitro/blob/9888d195fad804e9480dfe3441f8b8df310c95f4/nitro-protocol/contracts/interfaces/IMultiAssetHolder.sol#L77) event I think it's technically possible to have multiple events for a channel in the same block but we wouldn't expect it to happen if everyone is running our protocols.

 That's because the `deposit` function has an [expectedHeld](https://github.com/statechannels/go-nitro/blob/9888d195fad804e9480dfe3441f8b8df310c95f4/nitro-protocol/contracts/MultiAssetHolder.sol#L40) argument that it checks against the chain state.

This means for two transactions to be included, the second transaction must have an incremented `expectedHeld` based on the first transactions change to state. IE:
- TX : `Deposit(channelId=0xf00, amount=5, expectedHeld=0)`
- TX2: `Deposit(channelId=0xf00, amount=5,expectedHeld=5)`

TX2 has to be submitted with an `expectedHeld=5` to account for TX1 adding 5 to `held`.

This wouldn't happen running our direct fund protocols, since it would always wait for the first deposit to be confirmed before submitting the second deposit.  That said it could happen if someone specifically constructed a transaction that contained two deposit transactions somehow, knowing that go-nitro might not properly handle that situation.

I'm also unsure if this applies to our other events and functions in our smart contract. @geoknee or @NiloCK  probably know more!

**Comment by geoknee** [comment]
> Is there anything that enforces the restriction referenced in this comment that says a `Channel` can only be updated by a `chainEvent` that has a `BlockNum` greater than the block number previously seen? https://github.com/statechannels/go-nitro/blob/main/channel/channel.go#L322

No, that comment is stale and I should have removed it in #1591. I made this fix https://github.com/statechannels/go-nitro/pull/1612 

@lalexgap is right that it might be only in the case of malicious or unexpected behaviour that the intra-block index would matter. But, if it isn't a huge amount of effort to handle that I don't see why we shouldn't. I think in the case of challenge / checkpoint, two competing transactions can "race" each other and get included in the same block in either order and still execute. So it seems less unlikely for the situation to crop up there. 

In #1591 I wanted to try and push all of the logic around turn number and index with a block into the chain service. @bitwiseguy do you think that's possible or do you prefer to put the protection into the `Channel` class?

**Comment by bitwiseguy** [comment]
> In https://github.com/statechannels/go-nitro/pull/1591 I wanted to try and push all of the logic around turn number and index with a block into the chain service. @bitwiseguy do you think that's possible or do you prefer to put the protection into the Channel class?

To me it seems safer to put logic in the `Channel` class to protect its data rather than relying on an external component (`chainservice`) to only feed it sanitized data. Also, it could be useful to store the `lastUpdated` blockNum on the `Channel` in case a user wants to know when the channel was last changed. 

However, it's certainly possible to isolate the data sanitation logic to the `chainservice`. Here are a few questions to help us make the decision:

1. Is the `chainservice` the only service that can trigger updates to a `Channel` or are there other services that can do this and would need additional logic to ensure the data is not stale?
2. What "logic around turn number" are you referring to? Does any of that exist in the `chainservice` now or is that something we need to add?

Whether we protect `Channel` updates within the `Channel` logic or in the `chainservice`, it seems like we should keep track of `txIndex` in addition to block number in case there are multiple events related to a single channel within the same block.

**Comment by geoknee** [comment]
> To me it seems safer to put logic in the Channel class to protect its data rather than relying on an external component (chainservice) to only feed it sanitized data.

Fair enough, perhaps that does make the most sense after all. 

1. Currently the `chainservice` drips information to the engine, which calls [`Channel.UpdateWithChainEvent`](https://github.com/statechannels/go-nitro/blob/024da44e716a942629666d776b66b66f93f95185/channel/channel.go#L323). However, we have multiple `chainservice` implementations (it is only an interface). So your suggestion to put the logic in the `Channel` class would reduce duplication across current and future chain services.
2. By "logic around turn number" I mean logic ensuring that events being played / replayed / replayed to the `Channel` class in a shuffled order leave the `Channel` in a state consistent with the actual on chain blockchain state. This overlaps somewhat with the functionality of the go-nitro node to look back in time and process events from before it was started up. You had started to work towards that functionality here https://github.com/statechannels/go-nitro/pull/1581 for example. 

> 

Whether we protect Channel updates within the Channel logic or in the chainservice, it seems like we should keep track of txIndex in addition to block number in case there are multiple events related to a single channel within the same block.


Agreed. I believe that the index is readily available in Ethereum logs.
