### ISSUE TITLE
`panic: send on a closed channel` in `TestRpcWithNats` test

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1645]
https://github.com/statechannels/go-nitro/actions/runs/6102333531/job/16560598157

**Comment by lalexgap** [comment]
I think this may be an issue with nat based on a brief investigation of their codebase. When `Subscribe is called` nats starts a go-routine [WaitForMsgs](https://github.com/nats-io/nats.go/blob/8e75bfdad8e585f6fba1084c727c92b304e178bb/nats.go#L2996C8-L2996C8). 

It looks like `WaitForMsgs` just checks a [closed boolean](https://github.com/nats-io/nats.go/blob/8e75bfdad8e585f6fba1084c727c92b304e178bb/nats.go#L2996C8-L2996C8) to determine if it should exit. However based on your experience this can lead to problems, since it's possible that the `closed` var gets set just after the `WaitForMsgs` function checks it, resulting in attempting to deliver a message after close is called.

This is based on brief investigation so it's possible I'm missing something that would prevent that.
