### ISSUE TITLE
Investigate myIndex on ledger channels

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#268]
It's possibly a smell that this change didn't make a difference?

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/261#r810124799_

**Comment by geoknee** [comment]
`myIndex` is used in methods such as `PreFundSignedByMe()` and `myDestination`. Since those are used at the funding stage of channels, and the bug was discovered in a utility that skips over that step, it is inconsequential at the moment. That said, it seems like a bug waiting to happen so we should fix it.
