### ISSUE TITLE
Direct funding protocol might overfund channel

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#314]
The direct funding protocol condition for whether to submit a deposit transaction is https://github.com/statechannels/go-nitro/blob/b4b0d9b3493482b67f4db0e9be4449fa34631753/protocols/directfund/directfund.go#L171

There is a scenario where:
1. The funding protocol runs and submits a deposit transaction.
2. Another deposit transaction will be submitted if the protocol runs again before the initial deposit transaction succeeds.

**Comment by NiloCK** [comment]
This is a specific case of the general problem that the engine doesn't remember sending chain transactions until it later reads them back form the chainservice.

Probably: the chainservice should keep a list of pending transactions which
- can be referenced by protocols in order to halt and emit something like `WaitingforChainTx`
- can be used by the chainservice itself as a guard against double spends

**Comment by geoknee** [comment]
Another way to solve this is to have the direct funding objective store a flag so it remembers if it has previously declared the side effect in question? It sets this the first time, and then checks it later and skips sending the side effects.
