### ISSUE TITLE
Should ConsensusChannel use a mix of named fields and embedded structs

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#399]
Currently our ConsensusChannel is made up of both [named and anonymous struct fields](https://github.com/statechannels/go-nitro/blob/6164820f885fbcef832b46f7bc3458db0626dcb6/channel/consensus_channel/consensus_channel.go#L21). Would it be more ergonomic to use names for all fields?

**Comment by andrewgordstewart** [comment]
What is an anonymous struct field? When should I use one, and when should I avoid it?

**Comment by geoknee** [comment]
This is an example of struct embedding https://octo.vmware.com/golang-embedding/. @NiloCK is our expert on this!

**Comment by geoknee** [comment]
My rough understanding of struct embedding is, 'about as close to inheritance as you can get in Go'. 

I would say it is marginally more ergonomic to have the struct embedded in this way, since we can do: 
```go
consensusChannel.ChannelId()
```
instead of needing to do:
```go
consensusChannel.fixedPart.ChannelId()
```
It saves a few keystrokes. 

We are (roughly) saying that a `ConsensusChannel` _is_ a `FixedPart`. We do something similar here:
https://github.com/statechannels/go-nitro/blob/5e2c2df402ac66eb5b9d9b2fc1c7c9f43d56cdfb/channel/virtual.go#L9-L11
where we are (roughly) saying that a `SingleHopVirtualChannel` _is_ a `Channel`.

**Comment by lalexgap** [comment]
> My rough understanding of struct embedding is, 'about as close to inheritance as you can get in Go'.
> 
> I would say it is marginally more ergonomic to have the struct embedded in this way, since we can do:
> 
> ```go
> consensusChannel.ChannelId()
> ```
> 
> instead of needing to do:
> 
> ```go
> consensusChannel.fixedPart.ChannelId()
> ```
> 
> It saves a few keystrokes.
> 
> We are (roughly) saying that a `ConsensusChannel` _is_ a `FixedPart`. We do something similar here:
> 
> https://github.com/statechannels/go-nitro/blob/5e2c2df402ac66eb5b9d9b2fc1c7c9f43d56cdfb/channel/virtual.go#L9-L11
> 
> 
> where we are (roughly) saying that a `SingleHopVirtualChannel` _is_ a `Channel`.

That makes sense to me! 

Although maybe a [SignedProposal](https://github.com/statechannels/go-nitro/blob/main/channel/consensus_channel/consensus_channel.go#L209:L209) should embed a `Proposal` instead of a `signature`?

**Comment by geoknee** [comment]
I think it embeds both? Not sure I follow you...

**Comment by geoknee** [comment]
I'll close this because I think the original question has been answered. Let's open a new one if there are outstanding questions about this or other structs.
