### ISSUE TITLE
Vars.Add uses a value receiver but modifies the guarantees map

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#400]
Currently Vars.Add uses a [value receiver](https://github.com/statechannels/go-nitro/blob/ag/receive/channel/consensus_channel/consensus_channel.go#L186:L186), which mean the receiver is a shallow clone. However `Add` calls `DivertToGuarantee` which modifies the `guarantees` map on the `Outcome`. Since maps are reference type the shallow copy still points to the same map as the original.

This can be dangerous as you might not be aware you're modifying the underlying map.

```	currentVars := Vars{TurnNum: 5, Outcome: currentOutcome}
	current := SignedVars{Vars: currentVars, Signatures: [2]*state.Signature{nil, nil}}
	proposal := add(current.TurnNum+1, 5, channelId, alice.Destination(), bob.Destination())
	fmt.Printf("current BEFORE add is called: turn num %d, guarantees length: %d\n", currentVars.TurnNum, len(currentVars.Outcome.guarantees))
	_, _ = currentVars.Add(proposal)
	// Current still has the previous turn number but now it includes a guarantee
	fmt.Printf("current AFTER add is called: turn num %d, guarantees length: %d\n", currentVars.TurnNum, len(currentVars.Outcome.guarantees))
```
Outputs:
```
current BEFORE add is called: turn num 5, guarantees length: 0
current AFTER add is called: turn num 5, guarantees length: 1
```

**Comment by lalexgap** [comment]
I think we either: 
- Add a clone function to LedgerOutcome so we can clone the map and Add can return an independent vars.
- Modify `Add` to use a pointer receiver and modify the vars in place(instead of returning new vars)

**Comment by andrewgordstewart** [comment]
We can chalk this up to my novice go ability.

How should I have chosen between these two options?

**Comment by andrewgordstewart** [comment]
Copied from slack:
> Can we just change it to a pointer receiver? Is the intention to mutate the receiver or to return a (modified) copy?

We might not want to modify c.current in place as we are processing the queue -- if we come across an invalid change, then we want to leave `current` as it is.

What is the best way to accomplish this?

**Comment by geoknee** [comment]
Option 3: (best)?
* have `Add` take a pointer receiver
* document it as returning a modified deep copy
* implement `Vars.Clone()`
* Add generates a clone as its first step, and then proceeds to mutate the copy. If there is an error modifying the copy, Add returns an empty type and an error, as is idiomatic and as we do elsewhere in the codebase (e.g. in `objective.Crank()`).
* Instead of doing `vars, err = vars.Add(...)` we do something like 
```go
newVars, err := vars.Add()
if err !=nil {
newVars = vars
}
```

**Comment by andrewgordstewart** [comment]
> have Add take a pointer receiver

I was curious why this makes the most sense. Being a value receiver means `Add` already receives a clone of the caller -- the problem is that some of the values of the clone are pointers, and the pointers may point to shared values. So, one could leave `Add` as a value receiver, but if we wanted to return a deep copy, we'd have to do something like 15cc14b01c26c8a153499ce0e9c3d99c6628877f.

Going through https://github.com/golang/go/wiki/CodeReviewComments#receiver-type did not definitely rule out that approach. So, I'm happy with

> Finally, when in doubt, use a pointer receiver.

**Comment by geoknee** [comment]
https://github.com/statechannels/go-nitro/commit/15cc14b01c26c8a153499ce0e9c3d99c6628877f is an interesting approach. Maybe a matter of personal preference but I find it more explicit to construct a clone "from scratch" by reading existing data, rather than the two-step process of i) constructing a shallow clone via a value receiver, and then ii) going about changing its members by replacing them with new objects.

**Comment by andrewgordstewart** [comment]
Following the conversation [here](https://statechannels.slack.com/archives/C02CWRSH77X/p1648318876223959), I am curious if it makes sense to _only use pointer receivers_ as a rule of thumb. @geoknee, this would align with your personal preference (which I might agree with!)

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/go-nitro/pull/415
