### ISSUE TITLE
Seemingly improper check passes in `TestGetObjectiveByChannelId`

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#428]
https://github.com/statechannels/go-nitro/blob/8ea86b54c0128667a89f295434b2d9eeffa6afa6/client/engine/store/mockstore_test.go#L66

In this case (AFAICT) `got` is a `protocols.Objective` and want is a `directfund.Objective`. Yet the comparison is done between `got` and `&want` (the address of want).

I'm confused about why this is!

If I change it so I compare` got` and `want` directly, then I get a nonzero diff (I think because of some difference in types, rather than values). I think that is probably the direction we want to move in.

**Comment by NiloCK** [comment]
Note: the above observation is on a slightly out-of-date version of the test code, but the same situation occurs. In the current version, this coercion occurs in constructing the slice of `wants` instead

```
wants := []protocols.Objective{}
dfo := td.Objectives.Directfund.GenericDFO()
vfo := td.Objectives.Virtualfund.GenericVFO()
wants = append(wants, &dfo) // here
wants = append(wants, &vfo) // and here
```

What follows is my best understanding:

The non-zero diff when `got` and `want` are directly compared is (from memory) that the `want` value is prefixed with a `&`.

The root issue is that `protocols.Objective` is an interface type, and interface types are always pass-by-reference. In contrast, `directfund.Objective` is a struct, which can be (and is, in this case) passed by value.

Note that internally the `mockstore` performs [the same address-indirection](https://github.com/statechannels/go-nitro/blob/f42a06d76128a445f9a10c5a46a6894fec4d5237/client/engine/store/mockstore.go#L285) in order to comply with returning a `protocols.Objective` rather than the more specific `directfund.Objective`.


`cmp.Diff` here must receive the returned `protocols.Objective` by pointer address reference, since that's how those objects are passed around, but it recognizes the walked object as being different than the same thing, or a different-but-equal thing, passed by value. Passing the concrete type (`directfund.Objective`) by a reference allows cmp.Diff to start reading each object from the same point - its memory address.

**Comment by andrewgordstewart** [comment]
> The root issue is that `protocols.Objective` is an interface type, and interface types are always pass-by-reference.

I understood that everything in go is pass-by-value (but some values are pointers, ie. the value you're passing is a reference). I'm trying to reconcile this quote, which contradicts my understanding.

Maybe this is true?
> The value of an interface type is a pointer to the value of an implementation of the interface?
