### ISSUE TITLE
Rename consensus_channel to two_party_ledger

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#429]

**Comment by geoknee** [comment]
Just to head off any more attempts to resolve this issue: I wonder if we should keep the name as-is for now. This is mostly because (I believe) it is easier to have the discussion around the `Channel` <> `ConsensusChannel` relationship (e.g. questions such as "should they be somehow merged") with the current name. I don't think we would stand to gain that much if we were to rename it, while I do think there is potential for creating confusion or at least more mental overhead if we were to do so.

**Comment by lalexgap** [comment]
Closing as per https://github.com/statechannels/go-nitro/issues/429#issuecomment-1123552695
