### ISSUE TITLE
`GetObjectiveByChannelId` is not fully specified

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#490]
During the lifecycle of any given channel `c`, we expect **at least two** objectives to "point to" `c`.

For instance, a ledger channel is
1. directly funded, managed by some `DFO` (direct-fund objective)
2. directly defunded, managed by some `DDO`

Currently, when [`Engine.handleChainEvent` is called](https://github.com/statechannels/go-nitro/blob/2615ed67b6cb7aebd84553400b5ab635979cb109/client/engine/engine.go#L153),
1. an objective `o` is fetched via `GetObjectiveByChannelId`
2. an "objective event" `e` is created
3. `o.update(e)` is called
4. `o.crank()` is called

What should happen if `DFO` and `DDO` both existed in the store? Should that be impossible?

(inserted by @NiloCK) Related **Todo:** `GetObjectiveByChannelId` has no explicit tests.

**Comment by andrewgordstewart** [comment]
Furthermore, what should happen if a chain event is triggered for a ledger channel?

In this case, `GetObjectiveByChannelId` may return:
- an objective running for the ledger channel
- any virtual fund/defund objective which involves the ledger channel

**Comment by geoknee** [comment]
Here are some options: 

1. Maintain the following principle: A channel may be owned by exactly one approved Objective at any given time. 



A DFO and a DDO should not both be approved and crankable at the same time. When a DDO exists and is approved, any DFO for that channel should have been terminated. Hence, GetObjectiveByChannelId mostly stays the same (perhaps a rename), and we solve the problem by carefully managing Objectives and their relation to Channels. 


```
event --> objective-bar --> channel
```
                  objective-baz
event --> objective-bar --> channel

3.  The store could have an API like `GetDirectFundObjectiveByChannelID`, `GetDirectDefundObjectiveByChannelID`, etc.  The engine inspects chain events to infer their type. Deposit events are routed to a DirectFundObjective (if it exists), and AssetTransferred events are routed to a DirectDefundObjective (if it exists). Challenge events spawn a new objective. If the objective does not exist, either it is spawned or the event is dropped.

4. Instead of routing events to objectives, we route them directly to channels. I.e. channels could have an `update()` method. In this model, the engine looks up which objectives are interested in a channel that was just updated, and cranks all of them. 




But the problem is broader than that

**Comment by kerzhner** [comment]
Thanks for outlining the options @geoknee! Do we foresee use cases where multiple objectives will be active for a channel simultaneously? If not, it might be a good idea to restrict active objectives to 1 regardless of which approach above we adopt.

**Comment by geoknee** [comment]
> Perhaps we want to allow a ledger channel to be subject to a VirtualFundObjective for some channel V, at the same time as being subject to a TopUpLedgerChannel objective

I think this is a possible use case. Imagine that you are a hub and spot that your ledger channel is getting low on funds. It would be nice if you could spot this early, and get it topped up without having to pause the service you are providing by virtually funding new channels. 

I think we are probably quite a long way off from being able to support that, though.

**Comment by andrewgordstewart** [comment]
Summary of meeting notes:
# Objective ownership
It is a useful principle to be able say "At most one objective is running for a single channel at a time".

There are a few options of maintaining this invariant:
- there can be an `activeObjectives` collection, keyed by the objective's "target channel" id. When objectives are completed, they are moved
- an objective can store whether it's active or not in a `status` field. The store could ensure that at most one objective
- a `Channel` can point to its active objective (if there is one)

# "expected" chain events

We only expect chain events for ledger channels. The two types of expected events are:
- deposits (for directfund & top-up objectives)
- withdrawals (for directdefund & partial withdrawal)

Taking advantage of this invariant, we can figure out how to direct chain events.

If a deposit event comes in, there should be a direct fund or top-up objective running for that channel.

If a withdrawal event comes in:
- there could be a direct-defund objective running for that channel. In this case, the ledger channel's outcome _should not include any guarantees_, so the only channel (and therefore the only objective) that cares about the event is the direct-defund objective
- there could be a partial-withdrawal objective running. There are some details to work out in terms of how this would affect virtual channels & their objectives.


# "unexpected" chain events
An unexpected event might arrive for an arbitrary channel at an arbitrary time.

If it's a `challenge` event, we either need to recover from the challenge (via `checkpoint`) or recover funds. The wallet would have to determine:
- is this challenge for a virtual channel or a ledger channel?
and start the appropriate challenge protocol.
