### ISSUE TITLE
ChainId is hardcoded in production code

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#601]
We have a spattering of TODOs for this, but no issue to track it so far. 

The issue is made worse by our using a mixture of `0` and `9001` (and one case of `1337`) for chain id in our test code.

**Comment by NiloCK** [comment]
The `1337` used in the test code is a requirement of the test chain utility being used (approx: geth/backends/simulatedBackend). This requirement is documented inline in a number of places.

The "problem" usage of hard-coded `1137` is in `directfund.go`

**Comment by lalexgap** [comment]
We're running into this with testground on wallaby. The objectives construct states with a chain of [1337](https://github.com/statechannels/go-nitro/blob/5d8bdf0cc68d375eb805fa34a69585a71306667c/protocols/directfund/directfund.go#L61) which fail the `_requireCorrectChainId` check when concluding.

Our hardhat docker instance is using a chain of of [1337](https://github.com/statechannels/hardhat-docker/blob/9f9fbee81fa7a5061d361572bb051a5d707c622c/hardhat.config.local.js#L34) which is why that works.

**Comment by geoknee** [comment]
Tagging https://www.notion.so/statechannels/RFC-16-Cross-chain-Nitro-c8d9aee508ca4f9885d2b20f09aa0276, where part of the proposal is to remove checks on the chain id from the adjudicator (even from the off chain state entirely).

It may be worth us pinching off that part of the proposal, which is probably justifiable in its own right. It would solve this issue easily.

**Comment by geoknee** [comment]
I suppose there are two separate issues here, which the issue title doesn't quite do justice to. EVM chains have a chain id, we need to know that and to include it in transactions in order to clear the first hurdle when interacting with that chain. Then, there is another check (which we impose in our smart contracts), that the off chain commitments match the chain id where a channel is being managed. It's only the latter check that we have the choice to remove.
