### ISSUE TITLE
Create ts helper to expect a transaction to succeed

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#855]
While testing contracts using jest it is a common thing to expect a transaction, which does not return anything, to succeed. Thus, a helper, alike `expectRevert` is needed.

Some possible implementations:
- checking returned object/array to be empty
``` ts
async function expectSucceed(fn: () => void) {
  const txResult = (await fn()) as any;
  
  // As 'requireStateSupported' method is constant (view or pure), if it succeeds, it returns an object with returned values
  // which in this case should be empty
  expect(txResult.length).toBe(0);
}
```

- `try/catch/finally`
``` ts
async function expectSucceed(fn: () => void) {
  try {
    await fn();
  } catch (e) {
    // ?
  } finally {
    assert(true);
  }
}
```

**Comment by nksazonov** [comment]
`expectRevert` is defined in `@statechannels/devtools`, thus implementing `expectSucceed` there seems logical.

**Comment by geoknee** [comment]
Nit: I think in these tests we are actually not executing a _transaction_. If we were, we could inspect the transaction receipt for clues about whether it was successful. 

In fact we are actually using the `eth_call` endpoint, which generally returns a value instead of a transaction receipt. In this case as you say, the returned value is empty because in solidity we do not return anything from the function. 

Another approach you could use, which we have used in the past, is to force the execution of an actual transaction to test the method.

**Comment by geoknee** [comment]
Yet another way, which might be simplest, would be to just call the method without using any special helpers. And add a comment each time to explain that should the call `revert`, an error will be thrown and the test will be failed.

**Comment by nksazonov** [comment]
> Yet another way, which might be simplest, would be to just call the method without using any special helpers. And add a comment each time to explain that should the call `revert`, an error will be thrown and the test will be failed.

Yes, I agree this method is the simplest. Isn't not executing any assertion explicitly in the test and relying on thrown error if anything goes wrong a bad practice?

**Comment by geoknee** [comment]
Perhaps... in that case, 

> checking returned object/array to be empty

seems the better of your two proposals. I'm not sure it is worth adding this to @statechannels/devtools right now.

**Comment by nksazonov** [comment]
Okay will add the method `expectSucceed` to `go-nitro/nitro-protocol/src` then.
