### ISSUE TITLE
The engine does not guarantee to process ledger proposals in a sorted order

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#885]
We're not using a sorted list of proposals when [handling a message](https://github.com/statechannels/go-nitro/issues/883) containing proposals.

I think this means that it's possible to handle a proposal out of order, although I haven't seen a crash or any issue attributable to this. Most likely the proposals are mostly sorted anyways.

**Comment by lalexgap** [comment]
This is an easy change. We should make it and compare benchmarks.

**Comment by geoknee** [comment]
It would be nice to have some clarity around why this change is important. Is it just a performance thing? Or is it crucial for correctness (and we haven't run into problems yet because...).

**Comment by geoknee** [comment]
After some investigations...

* It is important for the engine to process the ledger queue "in order" for a given ledger channel. That is to say, if the engine tries to crank a virtual fund objective with a proposal having a  "future" `turnNum` (one for which the ledger channel has not yet processed the preceding proposal) it will be **dropped**. Because since ADR 4 we rely on redundancy in the ledger protocol (proposals are never re-sent, for example), dropping a proposal would lead to the ledger protocol completely stalling. 
https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/protocols/virtualfund/virtualfund.go#L86-L87

* it does not seem important (at this point) for proposals to be sorted by channel Id, since each proposal will lead to an independent crank:
 https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/client/engine/engine.go#L255-L279
 
* There may be some performance / scheduling considerations in future about processing proposals for the same objective in a batch (or having some other principle about prioritising things) but at present I don't think we would expect anything really very interesting to change if we sorted by channel id. 
* it **may** be helpful to sort by channel id for debugging / logging purposes. 
* at the present time we only ever construct messages with proposals for a single channel id, with proposals already sorted by turn number:
https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/protocols/virtualfund/virtualfund.go#L658-L659
 Therefore all of the sorting functions considered in #1015 and #1023 aren't actually doing anything
* we should consider what could change in future (implementation details not pinned down by any current specification or runtime check). Would those sorting functions get us out of trouble, then? Or do they constitute **noise** at the moment (many lines which don't actually do anything). We could replace them with a bit of well-placed documentation requiring messages to be" constructed with sorted turn number when channelIds are equal" (i.e. sorting function from #1023).
